language: ruby
rvm:
  - 1.9.3
env: DB=postgres
before_script:
  - "psql -c 'create database oblique_test;' -U postgres"
script:
  - "RAILS_ENV=test bundle exec rake --trace db:migrate spec guard:jasmine cucumber"
