common: &common
  adapter: postgresql
  host: localhost

development:
  <<: *common
  database: oblique_development

test: &test
  <<: *common
  database: oblique_test

cucumber:
  <<: *test

# for TravisCI
postgres:
  adapter: postgresql
  database: oblique_test
  username: postgres
